name: "Connect Publish (manual)"
on:
  workflow_dispatch:
    inputs:
      namespace:
        required: true
        type: string
      inputs_data_version:
        required: true
        type: string
      environment:
        description: "The environment to deploy to"
        required: true
        type: string
        default: "development"
  workflow_call:
    inputs:
      namespace:
        required: true
        type: string
      inputs_data_version:
        required: true
        type: string
      environment:
        description: "The environment to deploy to"
        required: true
        type: string

jobs:
  connect-publish:
    name: "Connect Publish: ${{ inputs.namespace }} [${{ inputs.environment }}]"
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: ${{ vars.RSCONNECT_URL }}nhp/${{ inputs.namespace }}/inputs

    steps:
      - uses: actions/checkout@v6

      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          extra-packages: |
            any::rsconnect
            any::cpp11
            any::fs
            any::progress
      - name: Generate manifest
        run: Rscript dev/generate_manifest.R

      - name: Upload manifest
        uses: actions/upload-artifact@v7
        with:
          name: manifest
          path: manifest.json

      - name: Publish Connect content
        uses: rstudio/actions/connect-publish@main
        env:
          CONNECT_ENV_SET_AZ_STORAGE_CONTAINER: ${{ secrets.AZ_STORAGE_CONTAINER }}
          CONNECT_ENV_SET_AZ_STORAGE_EP: ${{ secrets.AZ_STORAGE_EP }}
          CONNECT_ENV_SET_NHP_API_KEY: ${{ secrets.NHP_API_KEY }}
          CONNECT_ENV_SET_NHP_API_URI: ${{ vars.NHP_API_URI }}
          CONNECT_ENV_SET_NHP_MODEL_RUN_PROGRESS_URI: ${{ vars.NHP_MODEL_RUN_PROGRESS_URI }}
          CONNECT_ENV_SET_NHP_INPUTS_DATA_VERSION: ${{ inputs.inputs_data_version }}
          CONNECT_ENV_SET_NHP_OUTPUTS_URI: ${{ secrets.NHP_OUTPUTS_URI }}
          CONNECT_ENV_SET_FEEDBACK_FORM_URL: ${{ secrets.FEEDBACK_FORM_URL }}
          CONNECT_ENV_SET_GOLEM_CONFIG_ACTIVE: "production"
        with:
          url: ${{ vars.RSCONNECT_URL }}
          api-key: ${{ secrets.RSCONNECT_API_KEY }}
          access-type: logged_in
          force: true
          dir: .:inputs
          namespace: nhp/${{ inputs.namespace }}
